apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: example-voting-app
spec:
  type: NodePort
  selector:
    name: db
    app: example-voting-app
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001

