apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis
    app: example-voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        name: redis
        app: example-voting-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      name: redis
      app: example-voting-app

