apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: example-voting-app
spec:
  type: NodePort
  selector:
    name: redis
    app: example-voting-app
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30000

