apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app
    app: example-voting-app
spec:
  type: NodePort
  selector:
    name: result-app
    app: example-voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005

