apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker
    app: example-voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: worker
      labels:
        name: worker
        app: example-voting-app
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      name: worker
      app: example-voting-app

